config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :twerks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "twerks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twerk.rb
class Twerk < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :twerks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def sign_in_params
    params.require(:user).permit(:email, :password)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/twerks_controller.rb
class TwerksController < ApplicationController
  before_action :set_twerk, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /twerks
  # GET /twerks.json
  def index
    @twerks = Twerk.all.order("created_at DESC")
    @twerk = Twerk.new
  end

  # GET /twerks/1
  # GET /twerks/1.json
  def show
  end

  # GET /twerks/new
  def new
    @twerk = current_user.twerks.build
  end

  # GET /twerks/1/edit
  def edit
  end

  # POST /twerks
  # POST /twerks.json
  def create
    @twerk = current_user.twerks.build(twerk_params)

    respond_to do |format|
      if @twerk.save
        format.html { redirect_to root_path, notice: 'Yeah! Baby, That is how you Twerk.' }
        format.json { render :show, status: :created, location: @twerk }
      else
        format.html { render :new }
        format.json { render json: @twerk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twerks/1
  # PATCH/PUT /twerks/1.json
  def update
    respond_to do |format|
      if @twerk.update(twerk_params)
        format.html { redirect_to @twerk, notice: 'More Twerk More FUN!.' }
        format.json { render :show, status: :ok, location: @twerk }
      else
        format.html { render :edit }
        format.json { render json: @twerk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twerks/1
  # DELETE /twerks/1.json
  def destroy
    @twerk.destroy
    respond_to do |format|
      format.html { redirect_to twerks_url, notice: 'I will miss that Twerk.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twerk
      @twerk = Twerk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twerk_params
      params.require(:twerk).permit(:twerk)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twerks_helper.rb
module TwerksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twerker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if flash[:notice] %>
  <div class="notification is-primary global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>
<nav class="navbar is-info">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-5">Twerker</h1>
    <% end %>
    <div class="navbar-burger burger" data-target="navbarExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
  <div id="navbarExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to 'New Twerk', root_path, class: "button is-info is-inverted" %>
          </p>
          <% if user_signed_in? %>
            <p class="control">
              <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
            </p>
            <p>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
            </p>
          <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
<%= yield %>
</body>
</html>

app/views/twerks/_feed.html.erb
<div class="column is-half">
  <% if current_user != nil %>
  <div class="box">
  <article class="media-box">
    <figure class="media-left">
      <p class="image is-64x64">
        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
      </p>
    </figure>
    <div class="media-content">
      <%= render 'twerks/form' %>
    </div>
  </article>
  </div>
  <% end %>

  <% @twerks.each do |twerk| %>
    <% if twerk.user != nil %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(twerk.user.email, size: 64, alt: twerk.user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= twerk.user.name %></strong></br>
            <small>@<%= twerk.user.username %></small>
            </br>
            <p><%= twerk.twerk %></p>
          </div>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to twerk, class: "level-item" do %>
                <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
              <% end %>
              <%= link_to edit_twerk_path(twerk), class: "level-item" do %>
                <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
              <% end %>
              <%= link_to twerk, method: :delete, data: {confirm: "Are you sure?"} do %>
                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
              <% end %>
            </div>
          </nav>
        </div>
      </article>
    </div>
    <% end %>
  <% end %>
</div>

app/views/twerks/_form.html.erb
<%= simple_form_for(@twerk) do|f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :twerk, label: "Let's Twerk", input_html: {class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Twerk NOW!", autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/twerks/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong><br />
              <small><%= current_user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Twerks</p>
            <p class="title is-6"><%= current_user.twerks.count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">123</p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Followers</p>
            <p class="title is-6">465K</p>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/twerks/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">
      Trends
    </p>
    <a class="panel-block">
      Trend 1
    </a>
    <a class="panel-block">
      Trend 2
    </a>
    <a class="panel-block">
      Trend 3
    </a>
    <a class="panel-block">
      Trend 4
    </a>
    <a class="panel-block">
      Trend 5
    </a>
  </nav>
</div>

app/views/twerks/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">
      Who to Follow
    </p>

  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src="https://bulma.io/images/placeholders/32x32.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>Fenfang Xu</strong>
            <small>@fenfangxu</small>
          </p>
        </div>
      </div>
    </article>
  </div>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src="https://bulma.io/images/placeholders/32x32.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>Fenfang Xu</strong>
            <small>@fenfangxu</small>
          </p>
        </div>
      </div>
    </article>
  </div>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src="https://bulma.io/images/placeholders/32x32.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>Fenfang Xu</strong>
            <small>@fenfangxu</small>
          </p>
        </div>
      </div>
    </article>
  </div>
  </nav>
</div>

app/views/twerks/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Editing Twerk</h1>
        <%= render 'form', twerk: @twerk %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', twerks_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/twerks/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/twerks/new.html.erb
<h1>New Twerk</h1>

<%= render 'form', twerk: @twerk %>

<%= link_to 'Back', twerks_path %>

app/views/twerks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Twerk:</strong>
  <%= @twerk.twerk %>
</p>

<%= link_to 'Edit', edit_twerk_path(@twerk) %> |
<%= link_to 'Back', twerks_path %>